---
title: "Tallies"
output: html_notebook
---

```{r read in}
library(tidyverse)
library(ggplot2)
#setwd("<YOURPATHWAY>")
wd <- getwd()
new.data<- read.csv(paste(wd,'/Data/MetaData.csv',sep=""), header=TRUE, sep=",") #MetaData saved feb 11th
data<- read.csv(paste(wd,'/Data/Data.csv',sep=""), header=TRUE, sep=",")%>% #Data.csv is saved .xlsx feb 10th
  select(StudyID:Comments) 
r.squared<- read.csv(paste(wd,'/Data/TraitR2.csv',sep=""), header=TRUE, sep=",") #R2 generated feb 11th 
```

Tallies and Counts
## Effect Size
using only traits we can calculate cohen's d for...
```{r numbers for cohens d}
#traits with data needed for cohen's d
test<-new.data %>% 
  filter(!is.na(MeanValue)) %>% 
  filter(!is.na(Number)) %>% 
  filter(!is.na(SD) | !is.na(SE))

new.data[!duplicated(new.data$TraitID),] %>% 
  group_by(Slope.type) %>%
  summarize(count = n())

test<-new.data %>% 
  filter(Slope.type == "South") %>% 
  group_by(TraitID) %>% 
  mutate(unique_drainages = n_distinct(Drainage))

test$Drainage.type<-ifelse(test$unique_drainages==1, test$Drainage, "Mixed")

test[!duplicated(test$TraitID),] %>% 
  group_by(Drainage.type) %>%
  summarize(count = n())
  
```

## North vs South Slope
Looked at the ratio of north to south in traits with both populations (histogram)
Also looked at how many traits have over 4 populations on both the north and south slope (48)
```{r ratio of north and south}
slope.ratio<-new.data %>% 
  group_by(TraitID) %>% 
  summarise(South = sum(Slope=="South"), North = sum(Slope=="North"), ratio = North/South)
#visualize only mixed slopes traits by the ratio of north to south, are they evenly mixed or mostly one?
slope.ratio %>% 
  subset(ratio > 0 & !(ratio == Inf)) %>% 
  ggplot(aes(x = ratio)) + geom_histogram()

#can we use a subset to look at traits that have enough north and south to have a R2 for each?
test<-slope.ratio %>% 
  filter((South>4 & North>4) |  (North == 0 | South == 0 )) #302 with over 4 in each slope or only one slope
<<<<<<< HEAD
 #231 south only with 4+ pops
 #29 north only with 4+ pops
=======
test %>% 
  filter(North==0) #231 south only with 4+ pops
test %>% 
  filter(South==0) #29 north only with 4+ pops
>>>>>>> b1c6acaf058d7d2b9c2df8a91cd2e06773c4fe8f
traits<-test %>% 
  filter(South>4 & North>4) %>% 
  select(TraitID)

traits<-left_join(traits, new.data, by = "TraitID")
summary(as.factor(traits$StudyID)) #only 2 studies :(
<<<<<<< HEAD

#Caroni and Oropuche Question, how many traits have more than 2 hp and lp in both oropuche and caroni?
traits_s<-new.data %>% 
  group_by(TraitID, Drainage, Predation) %>% 
  tally() %>% 
  filter(n>2) %>% 
  filter(Drainage == "Caroni" | Drainage == "Oropuche")

traits_s %>% 
  group_by(TraitID) %>% 
  tally() %>% 
  filter(n>3) #so there's 10 traits with 2 hp and lp in both caroni and oropuche
=======
>>>>>>> b1c6acaf058d7d2b9c2df8a91cd2e06773c4fe8f
```
##
Visualization and Plots
## R2 plots (old school visualization)
```{r R2 prep}
new.data<-left_join(new.data,r.squared, by = "TraitID")
new.data$R.2<-as.numeric(new.data$R.2)
```



```{r plots violin}
ggplot(data = new.data, aes(x=TraitType2, y = R.2, fill = TraitType2)) + geom_violin() 
ggplot(data = new.data, aes(x=TraitType1, y = R.2, fill = TraitType1)) + geom_violin() 

new.data %>% 
  filter(unique_slopes==1) %>% 
ggplot(aes(x=Slope, y = R.2, fill = Slope)) + geom_violin() 

new.data %>% 
  filter(unique_slopes==1) %>% 
ggplot(aes(x=TraitType2, y = R.2, fill = Slope)) + geom_violin()

new.data %>% 
  filter(unique_slopes==1) %>% 
ggplot(aes(x=TraitType1, y = R.2, fill = Slope)) + geom_violin()

#ggplot(data = new.data, aes(x=StudyType, y = R.2, fill = StudyType)) + geom_violin() 

#sex specific plots
new.data %>% 
  filter(Sex == "M" | Sex == "F") %>% 
ggplot( aes(x = Sex, y = R.2, fill = Sex)) + geom_violin()

new.data %>% 
  filter(Sex == "M" | Sex == "F") %>% 
ggplot( aes(x = TraitType2, y = R.2, fill = Sex)) + geom_violin()

new.data %>% 
  filter(Sex == "M" | Sex == "F") %>% 
ggplot( aes(x = TraitType1, y = R.2, fill = Sex)) + geom_violin()

```
##